version: '3.5'

services:
  cert:
    build: ./docker_certbot
    volumes:
      - ./docker_certbot/cert_stuff:/acme-challenge
      - ./docker_certbot/cert_stuff_etc:/etc/letsencrypt
      - ./docker_certbot/cert_stuff_var:/var/lib/letsencrypt
      - ./docker_certbot/logs:/var/log/letsencrypt
    depends_on:
      - nginx
  web:
    build:
      context: ./docker_django
    command: python3 /poll_app/HN_poll/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker_django:/poll_app
    expose:
      - 8000
    env_file:
      - ./docker_django/secrets.env
  nginx:
    build: ./docker_nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./docker_certbot/cert_stuff:/acme-challenge
    depends_on:
      - web
