version: '3.5'

services:
  web:
    build:
      context: ./docker_django
    command: python3 /poll_app/HN_poll/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./docker_django:/poll_app
    expose:
      - 8000
    env_file:
      - ./docker_django/secrets.env
  nginx:
    build: ./docker_nginx
    ports:
      - 443:443
    depends_on:
      - web