# Generated by Django 3.2.11 on 2022-01-17 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='nominee',
            name='intra',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nominee',
            name='votes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
