# Generated by Django 4.0.5 on 2022-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0005_auto_20220118_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id_42',
            field=models.CharField(max_length=201),
        ),
    ]
