# Generated by Django 4.0.5 on 2022-06-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0006_alter_candidate_name_alter_voter_id_42'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='voter',
            name='id_42',
            field=models.CharField(max_length=200),
        ),
    ]
